### PR TITLE
Fix compilation with glm version 0.9.6 or higher

### PR DESCRIPTION
**Pull request by gh2k**
Another compilation fix!

In glb 0.9.6, template types have been moved from glm::detail namespace into the glm root namespace because they've been deemed stable as from this version.

This patch conditionally defines the glm template namespace depending on which version is installed.

### CODE REVIEW

**Comment by mfeemster** [comment]
Ah, looks like it's been a while since I upgraded versions of glm (I love that library btw).

I'd prefer not to have version checking preprocessors in the code. I expect developers (including myself) to have the latest version.

I will just change all of the cases to use glm:: instead of glm::detail

Great catch, thanks!

**Comment by gh2k** [comment]
I don't think this is the best plan. On Linux & friends you're somewhat at the mercy of what your distro maintainer decides to install. For example, on my gentoo system which has a rather aggressive release cycle I get a very recent libglm. On Ubuntu 14.04, which a lot of people will be using as it's the most recent LTS, you still get libglm < 0.9.6, and there won't be an upgrade. apt-get install libglm-dev will always give you the same thing.

Similarly, on osx 'brew install libglm' gives me a specific version.

**Comment by mfeemster** [comment]
Ah ok, I didn't realize that. I figured installing libglm-dev would always give you the most recent. In that case, I'll go with your solution.

**Comment by gh2k** [comment]
There are probably less ugly (code-prettiness-wise) solutions to this. Probably the nicest solution would be to conditionally import the glm vector types as something new. e.g. :

````
#ifdef foo
template<class T>
using glm_tvec2 = glm::detail::tvec2<T, glm::defaultp>
#else
template<class T>
using glm_tvec2 = glm::detail::tvec2<T, glm::defaultp>
#endif
````

I can update the PR to use that if you prefer?

**Comment by mfeemster** [comment]
Yeah that's probably nicer. I can do it on my end, so don't worry about it. I'll play with it for a while and see what looks best. Thanks again.

**Comment by mfeemster** [comment]
I solved this in a slightly different way, so I'm going to reject this PR. You should be good to go now.

**Pull request closed without merging**
