### PR TITLE
modify Qt projects for building with Qt Creator (windows)

### PR DESCRIPTION
**Pull request by luyuju151**
modify Qt projects for building with Qt Creator (windows)
add build guide using Qt Creator and MSVC2013

### CODE REVIEW

**Comment by mfeemster** [comment]
Can I ask what the purpose of this PR is? You are enabling a build in QtCreator for a Windows system that already has VS on it. VS is a superior IDE, so if someone had it already, I assume they would just be using that.

Is this in anticipation of adding support for other compilers on Windows such as GCC and Clang?

**Comment by luyuju151** [comment]
If someone uses pre-built Qt for MSVC2013, native 64bit Qt Creator will be shipped with. Visual Studio is a good IDE, but as for a project not too large, lightweight Qt Creatir can do it as well.  When focusing on developing Qt UI, Qt Creator works more seamlessly, which can for example automatically add signal slots from Designer's right menu. I think letting people choose what they like to build fractorium is not a bad thing. So I modified the project files a little for Qt Creator windows, with little extra effort to maintain it in the future. Perhaps by doing this, further improvments on UI from other guys loving to use Qt Creator will be easier. 

I haven't considered other compilers, because I noticed CUDA and tbb for windows privide libraries as *.lib. More steps will be needed if someone wants to build with GCC or Clang.

**Comment by luyuju151** [comment]
OK...I give up, Fractorium uses so many template and virtual functions. When I trying to fix it that when the path includes unicode character, it reports "Could not load palette file, all images will be black. See info tab for details." relating to using string not wstring, Qt Creator constantly takes 100% CPU and freezes. Maybe this project is too large for Qt Creator ...

**Comment by mfeemster** [comment]
Yes, it's a large and complex project. Fractal flames are not an easy thing, hence why I've spent the last three and a half years on this effort.

Don't bother with the unicode stuff, I went down that path once myself. Every single string has to be converted to wstring, and then certain APIs expect regular string. It's a nightmare that is simply not worth it. Despite decades of work on internationalization, I've never seen a good way to actually do it. It's a complete mess, so I only support ASCII until someone comes up with a well-designed system.

Regarding the CPU usage of the build, VS does the same thing. It's a big build that can take advantage of multi-threading, so it will use all cores. I build all six projects regularly on Linux, so I'm positive QtCreator can handle it.

I will examine the details of the PR over the next few days and merge it if I can get it to build on my system.

**Comment by luyuju151** [comment]
Thanks! And one more time thanks for bringing up this great project!

**Comment by gh2k** [comment]
:+1: LGTM - thanks for the update, some people want to use a Free IDE on Windows if possible. :)

I haven't actually tested this on Windows, but I've read the changes and they look OK. @luyuju151 are you able to produce a working build with this?

I tried building on Windows in VS but I got fed up with all of the hardcoded dependency paths and there didn't seem to be a good way to manage dependencies there. $$EXTERNAL_LIB makes things easier.

**Comment by mfeemster** [comment]
@gh2k Managing dependencies on Windows is not as centralized as other OSes, so each project needs to be aware of where things are. I try to mitigate the pain of new builders with these instructions:

https://github.com/mfeemster/fractorium/wiki/Building

I'll hopefully get to this PR shortly after I finish a few other things.

**Comment by luyuju151** [comment]
@gh2k Yes, I'm using fractorium built from source according to this instruction that had just fixed the "pure virtual functionn call" error. Everything works fine except that the exe file icon is missing, but it doesn't affect the use of fractorium.

**Comment by mfeemster** [comment]
Finally had a chance to look at this. I am going to accept it, then do some manual merging since I've already done a commit to default.pri.

@gambhiro @luyuju151 The EMBER_ROOT variable is beginning to be a real pain. It will not build on my machine if it uses $$PWD. For some reason, that resolves to my home folder which is not where I have my source. It will only work for me if it's ./../../../

After I do this merge, we need to get that variable squared away so we stop breaking each others' builds.

**Pull request merged**
