### PR TITLE
Fix compilation on OS X

### PR DESCRIPTION
**Pull request by gh2k**
Apple's compiler disagrees with GCC on a few issues (usually, it's more pedantic), and the libraries aren't all in the same place, or included in the same way.

Also I had to work around a segfault in the compiler when compiling code with lambdas as default parameters. IMO this code was perfectly valid but crashes the compiler. I've filed a bug report and left the default params commented.

Finally I had trouble with the build system trying to deal with the precompiled headers as objective-c. Turning off precompiled headers fixes the problem, although this may not be the best way.

### CODE REVIEW

**Comment by gh2k** [comment]
May I just add:

Holy crap you have done amazing work with this project!

**Comment by mfeemster** [comment]
Hi Simon, thanks for getting in touch with me. Forgive my memory, but have
you contacted me here, or on Deviant Art before? Your name looks familiar,
but I can't quite call it.

So it appears you're aiming for a Mac build, that's great! I don't own a
Mac, so I haven't even begun to contemplate all the tricks/changes/hacks
I'll need to do to get it to run there. I am at work right now so I can't
spend too much time looking at it, but I will spend the next few days
checking out what you did.

Whenever someone emails me, I'm always curious what their
motivation/justification is. What brought you to Fractorium? Do you make
art on DA? How long did it take you to do all of this? I hope you didn't
blow a weekend on it! If you're ever wanting to do something in the code,
or have questions, please contact me first. There are definitely some
strange things in there that I can help clarify, which will save you time.
I must say I'm impressed that you got it all setup since I haven't added
documentation for getting Qt and all of that setup with non-Windows GCC.
That's something I need to add. Did you at least find the Windows build
instructions on the Wiki helpful?

Also, what other editors/renderers do you use? Apo, Chaotica, JWildfire,
Fractron, Silver Fractal. There's also another in Beta called Voidoria.

Thanks for the kind words as well! I appreciate it. I really wanted to help
move Fractal Flames editing and rendering forward with this project. The
documentation on the Wiki explains my process and intent. The existing
codebases out there, flam3 and Apophysis were not at all what I wanted, so
I made my own that was essentially a re-write/re-design of flam3 in C++
with GPU support. I dumped over 2 years of my life into it, so I hope
people find it useful. The project is by no means "done", but it's to a
stable point. I took a break on it over the past 6 months to just let
myself relax, and have only been adding minor updates. I still have a ton
of ideas that I want to try and it's just a matter of finding the time. I
hope to get back on it soon.

In the meantime, what's more important than adding fancy new features, is
making a website. Directing people to a github page is.... lame. I am in
the process of making one. It'll be nothing special, just a Wordpress theme
that I bought. But I hope to use it to clarify some things that I keep
getting asked over and over by people. I also want to do some writeups and
benchmarks on performance since that's an area that hasn't been too
thoroughly explored (at least on anyone else's sites I see).

Let me know what you think and I'll have a look at your patch over the next
few days. Thanks again for the unsolicited help!

-Matt
matt.feemster@gmail.com


On Wed, Jan 14, 2015 at 5:51 AM, Simon Detheridge <notifications@github.com>
wrote:

> May I just add:
>
> Holy crap you have done amazing work with this project!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mfeemster/fractorium/pull/1#issuecomment-69918203>.
>



-- 
*github.com/mfeemster/fractorium/wiki
<http://github.com/mfeemster/fractorium/wiki>*

**Comment by mfeemster** [comment]
Thanks Simon I appreciate the help, I will have a look shortly. Can you email me at matt dot feemster at gmail dot com? I've got a few questions. Thanks.

**Comment by gh2k** [comment]
Hi... :-)

You probably know me from the HD Electric Sheep render I did here:
http://blog.highlyillogical.org/electric-sheep-in-hd/

I used good ol' flam3 CPU, and it took a very long time. You mentioned this
project in the comments some time ago, and I've just started looking at it.

WRT the mac build. I've built it here using the changes I've pushed, and it
works. I've compared it to a Linux build using my updated code and both
build and run just fine, so I don't think I've introduced any breaking
changes. I haven't tried it on Windows. There weren't that many changes...
Just a few points where clang was a little bit more finnicky than gcc.

I didn't find the wiki, but I'm a very experienced programmer so I didn't
have any trouble getting the project built and running. If you'd like me to
produce a mac binary build for you that you can offer to download, I'd be
happy to do that and keep it updated.

I don't really do a lot of flame creation myself. I was looking at this as
a way to create more videos faster than churning them out on the CPU. I've
compared the output of a few of my tests to flam3, and they're as near to
identical as makes no difference, so I'll definitely be using this from now
on. My test frame renders in 55sec on my CPU, and 2.8sec with OpenCL! :-)

One thing I think will make a difference is delegating writing out the
individual frames from EmberAnimate in a separate thread to the renderer. I
find that on my system with my very beefy ATI card, it's spending nearly
50% of the time writing PNGs, which could be done more efficiently on the
CPU, leaving the GPU working on the next frame. Admittedly, I haven't
looked into this in any great detail.

Do you know if any of the other variations available as plugins for apo
would work in Ember if they were ported? I'm not really up on the
algorithm, but I've always wanted to animate some of the nicer flames that
I've found on deviantart and elsewhere, but due to lack of support for the
variations it's not been possible. I'd be happy to help port them across if
they'd be compatible, but I honestly don't know if you could animate them
in the same way as the existing ones. (I'm more of a software architect
than a mathematician!)

Thanks,
Simon

**Comment by mfeemster** [comment]
All good information, thanks!

Look through the Wiki, it explains a lot for both users and developers.

I have indeed thought about threading the file output, but have just never done it. I will add that to the next release, hopefully it'll speed things up.

Ember supports almost 300 variations: standard flam3 98 plus ~200 ported from Apo plugins. It also offers pre_ and post_ versions of almost all of them. This is perhaps overkill, as pre_ and post_ don't make sense for some, but creating them is mostly automated through macros so I left them in. The large number compiled as templates for both float and double, is why it takes so long to build:
 
~300 * 3 (reg, pre, post) * 2 (float, double) = ~1800 classes in the Ember dll. Ouch!

They are built in and do not use the pluggable architecture of Apo. That is one drawback of Ember. However, the current list is by no means fixed. If you have a list of variations that you'd like added, then please let me know and I'll give it a shot.

They are all "animatable" because animation is done in a generalized fashion. TBH, I haven't tested animation too much beyond basic functionality, so this would be a great area to really start beating on it.

Also, in the future I'd like to make an animation GUI to give the artist a much better tool for making animations.

**Comment by gh2k** [comment]
NICE! I'd started working on a fork of flam3 and trying to patch new
variations into that. You've done all the work for me by the sounds of it!

I'll have a play. I'm looking to make a 4k/HFR render so I'll keep you
posted. :-)

**Comment by mfeemster** [comment]
Ok sounds good! Also remember that the command line programs accept command line arguments in addition to env vars, unlike the flam3 ones which were limited to only env vars. I found that this made it easier to experiment. Use --help to see the available options.

**Comment by mfeemster** [comment]
I've looked over the changes and they appear fine, except for a couple of questions:

1) You added the 'template' keyword here in Renderer.cpp:
m_Samples[threadIndex][0].m_X = m_Rand[threadIndex].template Frand11<T>();

When I built with GCC, it didn't complain. Also, I use Frandxx<>() all over the place. If it's required here, why not everywhere else? Are you sure it's necessary here?

2) cl.hpp should be a system wide install, included with the video driver driver SDK. For that reason, I'd prefer not to keep a local copy because I'd have to keep manually updating it when new versions come out. Does Mac not install this anywhere on the system? Also, I purposely reference different versions of this file in the Visual Studio build settings when building for either Nvidia or AMD, because Nvidia doesn't support OpenCL 1.2 (curse them for that). We may need to do a similar thing with Mac, I think some of their desktop machines use AMD cards?

Let me know what you think. Thanks.

**Comment by gh2k** [comment]
Re: 1 - yes, it's a compiler error. Specifically, it says:
````
../../../Source/Ember/Renderer.cpp:1201:56: fatal error: use 'template' keyword to treat 'Frand11' as a dependent template name
                        m_Samples[threadIndex][0].m_X = m_Rand[threadIndex].Frand11<T>();
                                                                            ^
                                                                            template 
````
It seems pretty specific about wanting a template keyword right there... :-)

Re: 2, there is no cl.hpp deployed with osx, and there is no package for it. Accept wisdom is that you have to download it manually... See: http://stackoverflow.com/questions/23072367/cant-setup-opencl-on-mac-osx

I guess you could provide instructions in the documentation on how to download these files manually, but it makes life harder. WRT the different versions you set up from Visual Studio, what does the Linux build do about this? I didn't see anything about different cl.hpp files.

**Comment by mfeemster** [comment]
Ok, I guess if it wants the template keyword there, we can keep it. I still think it's strange that it doesn't require it elsewhere though.

We can include cl.hpp with the source then. My Linux builds were only done locally on my machine and have not been tested by anyone else. It's just early prototype stuff, so I haven't even gotten to the point of figuring out how I am going to do different builds for Nvidia vs. AMD. It's something I eventually need to do. I welcome any ideas on how we might do this on Linux.

BTW, I have made a prototype for threading the file output during animation last night and it does indeed speed things up. I will include it with your changes after testing/perfecting it.

**Comment by gh2k** [comment]
I can take a look at the Linux AMD vs. NVidia issue for you, if you like? I have access to machines with both.

I only have access to one mac, but as they're very Linux-like I anticipate the same fix working for both.

Very pleased about the threaded file output. For my use case it should speed things up a great deal... Thanks!

**Comment by mfeemster** [comment]
Yes, please do have a look at it for Linux/Mac. Let me know what you find. Thanks!

FWIW: On Windows, I have a two separate build configurations, Release and ReleaseNvidia. They have different include paths to point to the cl.hpp file in their respective SDK folders. I also do a few #defines. It's a hack, but until Nvidia supports OpenCL 1.2, it was the best we can do.

**Comment by mfeemster** [comment]
Alright Simon, do a pull, build and you should see the following:

-Your changes committed.
-Threaded writing for animation on the command line, and in the final render dialog in Fractorium.
-Miscellaneous bug fixes captured in the commit notes (peruse at your leisure).

Please test and if it goes well I'll make a new installer.

Is there another way I can get in touch with you? I have some questions/ideas about animation that I'd like to run by you since you're the only person who seems to be using that portion of the program. I'd really appreciate it.

Let me know what you think.

**Comment by gh2k** [comment]
Thanks for merging... 

It certainly seems faster when animating, thank you! :-)

You can contact me on "sd (at) sd (dot) ai" if you like. I'm using this code for another animation project right now... I'm having a couple of teething problems, but I'll raise as separate issues.

**Pull request merged**
