### PR TITLE
Ubuntu 15.10 nvidia

### PR DESCRIPTION
**Pull request by gambhiro**
I upgraded to Ubuntu 15.10 and a few things needed to be fixed to build.

Notably `opencl-headers` upgrades to 2.0 in 15.10. Among other changes `CL/cl.hpp` is no longer shipped with the package which frustrates [other people as well](https://github.com/clMathLibraries/clSPARSE/issues/120). As suggested there, I saved 1.2 in a vendor folder and use that in the include paths during compilation.

Also fixed an issue where `libOpenCL.so` is not found (not created by the dependency for some reason), so I added extra steps in `main.pro` such that `qmake` creates symlinks in local folders to use.

This now builds for me with `pbuilder` and I reckon is ready for an official Launchpad PPA.

### CODE REVIEW

**Comment by mfeemster** [comment]
The cl.hpp file is already in the deps folder, but this seems more comprehensive, so I'll remove that one in favor of these.

A question on the specific nvidia versioning:

opencl-headers (<< 2.0), nvidia-opencl-icd-352, nvidia-libopencl1-352

We are using OpenCL >= 1.2 and nvidia only recently added support for it. So we need to be sure the specific nvidia version you reference does indeed include their latest support for 1.2. Can you confirm that?

Thanks.

**Comment by mfeemster** [comment]
Also, this references nvidia specifically. We'll need to verify that an install built against nvidia libs still runs on a system with only AMD drivers installed. This works on Windows, but I'd like to verify it on linux as well. I have my own local builds working with AMD on linux, so I will test it with this in a few weeks to verify.

**Comment by gambhiro** [comment]
OpenCL 1.2 is recognized and enabled. My card doesn't seem to support SPIRO 1.2, so it actually slows down and doesn't speed up, but it spins the GPU instead of the CPU when I click the button.

Eventually I removed `opencl-headers` and `nvidia-opencl-icd-352` from the build dependencies. The latter was not needed and `opencl-headers` is now in `Build/include/vendor`.

In the end we will have to figure out how to remove `nvidia-libopencl1-352`, but something needs to provide the `libOpenCL.so` to build automatically on Launchpad.

**Comment by gambhiro** [comment]
Just a sec, I realized `ocl-icd-libopencl1` might work too instead of `nvidia-libopencl1`. Just running a build to see if that works.

**Comment by gambhiro** [comment]
OK, `ocl-icd-libopencl1` works too. So committed that as dependency. From what I gather, only the ICD driver needs to be vendor specific, so the user has to install the correct one for their card.

**Pull request merged**
