### PR TITLE
Script improvements

### PR DESCRIPTION
**Pull request by gambhiro**

### CODE REVIEW

**Comment by mfeemster** [comment]
Good job on the generic OpenCL lib.

For the version, instead of reading it from the changelog file, is there a way you can parse it out of EmberDefines.h?

#define EMBER_VERSION "0.9.9.2"

That would prevent us from having to keep it synced in two places. What do you think?

**Comment by gambhiro** [comment]
There can be more than one debian source package per "logical" version. Launchpad expects a unique version number for each, hence the `e` in `0.9.9.2e`, I prefixed it with letters while tweaking the sources for the Launchpad build. These tweaks can be even something as minor as a typo in the debian package description.

Say, when I'm working on getting a source to build, I would **not** want a script to mess with the changelog file, because it can cause Launchpad to reject the uploaded tarball.

I would rather have the script to test if the changelog version agrees with `EmberDefines.h`, and exit with an error if it doesn't.

Then whoever is doing the maintaining can do what is sensible right then, i.e. update the changelog, or `EmberDefines.h`, or comment out the test for some quick hack.

Does that make sense to you?

And how far should the two agree?

`0.9.9.2e-0ubuntu1` in the changelog means:

- source tarball `0.9.9.2e`
- `0` debian version
- `1` ubuntu version

**Comment by mfeemster** [comment]
That makes sense, they should at least agree on the part listed in EmberDefines.h, eg. 0.9.9.2

**Comment by gambhiro** [comment]
OK, this should do it. To be fair the letter postfix could have been avoided in theory, but the build tools and their checks are still obscure to me as well.

**Pull request merged**
