### PR TITLE
Linux mac 0.9.9.2

### PR DESCRIPTION
**Pull request by gambhiro**
Hello everyone. Please see the brief description below.

### CODE REVIEW

**Comment by gambhiro** [comment]
Briefly, these commits contain:

- `debian` folder for linux packaging, used by the `bzr dh-make` wrapper (#31)
- `.pro` files such that `qmake; make` in the project root should generate appropriate Makefiles and compile
- successful Mac build on OSX 10.10 66aa8fa
- look for in a few obvious folders for the palette list (#33), see 06d4c95
- `package-linux.sh` helper for `.deb` building and testing
- started Readme instructions for building from git

I'm sorry that individual features are not very linear or in cleanly separate commits. There was a lot of back-and-forth between issues while I was trying to get them work together.

**Comment by gh2k** [comment]
:+1: thanks

**Comment by gh2k** [comment]
Do you think it would be possible to package libember and libember-dev separately to fractorium, with libember as a Fractorium dependency? It's really not a biggie, but that would be the "proper" way ;)

**Comment by gambhiro** [comment]
@gh2k would the situation come up, reasonably often, where you wish to ship a new version of the libs to the user, but not a new version of the application? Honestly asking. I can't say, I've only just arrived.

My impression is the the libs and app are developing in such proximity at the moment, that if you shipped a new version of the libs, it would break the app.

**Comment by mfeemster** [comment]
Both of you are correct. However I prefer the practical to the theoretical, so let's just leave them together for now unless someone requests them to be separate in the future. We have a lot of big fish to fry right now so I'd rather not get sidetracked.

**Comment by gh2k** [comment]
Yeah fair enough. I've done a bit of noodling around with some stuff that uses libember, which if I were to make a .deb package for would then have to pull in Fractorium... Which isn't The Done Thing. But you're right, that's entirely theoretical atm. :)

**Pull request merged**
